### ISSUE TITLE
_trackerUrl to qstring procure SIGFAULT event

### ISSUE THREAD

**Issue by romain-neil** [pbek/qt-piwik-tracker#2]
in the cpp file, in the sendVisit function, the following line 217 cause sigfault error:
`QUrl url(_trackerUrl.toString() + QString("/piwik.php"));`
particuliary the toString method

**Comment by pbek** [comment]
Can you please explain in more detail and step by step what you did.

**Comment by pbek** [comment]
And which version of Qt on which platform are you using?

**Comment by pbek** [comment]
Do you have example code? What `trackerUrl` are you using?

**Comment by romain-neil** [comment]
I use Qt 5.13.0 and I call sendVisit function from a other class.
Code sample:
(in other function):
`sendTelemetry(QString("/change-prefix/") + QString(p));`
`void Core::sendTelemetry(QString p) {
    if(statisticsEnabled)
        piwikTracker->sendVisit(p);
}`
where piwiktracker is `PiwikTracker *piwikTracker;`
`_trackerUrl` is the parameter of the function `piwiktracker->sendVsit(p)`

**Comment by romain-neil** [comment]
I will try to use events instead of sendVisit

**Comment by pbek** [comment]
I use something similar for QOwnNotes at <https://github.com/pbek/QOwnNotes/search?q=sendVisit&unscoped_q=sendVisit> and never got a segmentation fault.
